### PR TITLE
websocket: fixes deduced conflicting types error on gcc 9.3

### PR DESCRIPTION
**Pull request by bramoosterhuis**
another fix when working with GCC 9.3

### CODE REVIEW

**Comment by bramoosterhuis** [comment]
complete error:
```
[build] /usr/include/c++/9/bits/stl_algobase.h:198:5: note:   template argument deduction/substitution failed:
[build] In file included from ../Source/plugins/../websocket/websocket.h:33,
[build]                  from ../Source/plugins/Module.h:31,
[build]                  from ../Source/plugins/Module.cpp:20:
[build] ../Source/plugins/../websocket/WebTransfer.h:339:63: note:   deduced conflicting types for parameter ‘const _Tp’ (‘long unsigned int’ and ‘uint32_t’ {aka ‘unsigned int’})
[build]   339 |                 uint16_t chunk = std::min(sizeof(buffer), size);
[build]       |                                                               ^
[build] In file included from /usr/include/c++/9/algorithm:61,
[build]                  from ../Source/plugins/../core/core.h:23,
[build]                  from ../Source/plugins/Module.h:27,
[build]                  from ../Source/plugins/Module.cpp:20:
[build] /usr/include/c++/9/bits/stl_algobase.h:246:5: note: candidate: ‘template<class _Tp, class _Compare> const _Tp& std::min(const _Tp&, const _Tp&, _Compare)’
[build]   246 |     min(const _Tp& __a, const _Tp& __b, _Compare __comp)
[build]       |     ^~~
```

**Review by pwielders — APPROVED** [review]
